import type { Metadata } from "next";
import { ButtonLink, Container, SectionHeading } from "@/components/ui";

export const metadata: Metadata = {
  title: "Sample Lesson",
  description: "See how HIRI combines expert teaching, deliberate writing practice, personalised feedback and Mentor guidance.",
  alternates: { canonical: "/sample-lesson" },
};

const lessonSteps = [
  ["1 · Learn", "Watch a focused video lesson with Shaanzae.", "Each lesson begins with Shaanzae teaching one clear creative-writing skill and showing why it matters before you put it into practice.", "Focused teaching. One clear objective. No unnecessary theory."],
  ["2 · Write", "You apply it in your own writing.", "A guided task asks you to make deliberate choices. Your ideas, language and voice remain your own.", "The goal is not to imitate. It is to make stronger choices for yourself."],
  ["3 · Coach", "Your writing is examined in depth.", "HIRI's Coach looks closely at the writing you actually submitted — how effectively you applied the lesson, the choices you made, where the writing is already strong and what may be holding it back. Its feedback is shaped by a system modelled on Shaanzae's teaching methods, so the guidance remains connected to what you have just been taught.", "It does not simply correct the piece. It helps you understand what to improve and why."],
  ["4 · Improve", "Use the feedback to make your next choices stronger.", "The purpose of feedback is not simply to improve one submission. It helps you recognise what stronger writing requires so you can apply that understanding again in the next lesson.", "Each lesson contributes to the writer you are becoming."],
];

export default function SampleLessonPage() {
  return <div className="page sample-lesson-page"><Container>
    <section className="sample-hero"><SectionHeading eyebrow="Sample lesson" title="See how HIRI turns an idea into better writing." description="A HIRI lesson is not simply something to watch. You learn a focused writing skill, put it into practice, receive personalised feedback and use that guidance to improve." as="h1" /><p className="page-lead">This sample shows the rhythm students follow throughout the four-week course.</p><p className="sample-proof">Learn with Shaanzae → Write → Deep feedback → Progress</p></section>

    <section className="section"><div className="lesson-cycle">{lessonSteps.map(([label, title, body, support]) => <article className="lesson-cycle-card" key={label}><p className="panel-label">{label}</p><h2>{title}</h2><p>{body}</p><strong>{support}</strong></article>)}</div></section>

    <section className="section sample-teaching"><SectionHeading eyebrow="A sample teaching moment" title="From telling the reader to making them feel it." description="One of the first shifts young writers learn is that stronger description does not come from adding more adjectives. It comes from noticing the right details." /><div className="writing-comparison"><article><p className="panel-label">Before</p><p className="writing-example">The room was old and frightening.</p></article><article className="look-closer"><p className="panel-label">Look closer</p><p>Instead of naming the feeling, ask:</p><ul className="list"><li>What can the character see?</li><li>What small detail feels wrong or unexpected?</li><li>What can be heard?</li><li>What might the character physically notice?</li></ul></article><article className="writing-after"><p className="panel-label">After</p><p className="writing-example">The door dragged across the floorboards as she pushed it open. A strip of wallpaper hung loose beside the window, moving slightly although the room was still.</p></article></div><p className="sample-note">The second version does not tell the reader to be uneasy. The details create the feeling.</p><p className="sample-emphasis">HIRI teaches students to understand why that difference works — so they can make the choice themselves in new writing.</p></section>

    <section className="section writing-task"><SectionHeading eyebrow="Now you write" title="Try the kind of decision a HIRI student would make." description={<>Imagine a character entering a place they have never seen before.<br /><br />Write <strong>80–120 words</strong> describing the moment without directly using words such as <strong>scary, beautiful, exciting, strange or sad.</strong><br /><br />Instead, make the reader understand the atmosphere through specific details, movement, sound or the character's reaction.</>} /><p className="task-prompt">What would you choose to make the reader notice first?</p></section>

    <section className="section feedback-section"><SectionHeading eyebrow="What feedback might focus on" title="Feedback should help you see your writing differently." /><div className="feedback-examples"><article><p className="panel-label">What is working</p><p>You chose a physical detail instead of naming the emotion. The reader can experience the scene rather than being told how to feel.</p></article><article><p className="panel-label">What to push further</p><p>Look at the final sentence. Is every description creating the same atmosphere, or is one detail there only because it sounds descriptive?</p></article><article><p className="panel-label">What to try next</p><p>Choose one detail that reveals the character's physical reaction. That can deepen the scene without explaining the emotion directly.</p></article></div><p className="sample-emphasis">HIRI feedback is designed to help the student make the next decision — not rewrite the piece for them.</p></section>

    <section className="section section-dark mentor-sample"><SectionHeading eyebrow="Beyond one lesson" title="The Mentor looks for development across your writing." description={<>The Coach works with the writing in front of you. The Mentor looks across your development.<br /><br />As you progress through HIRI, it brings together evidence from your lessons, feedback and reflection to identify patterns — where you are becoming stronger, where the same difficulty keeps appearing and what deserves your attention next.<br /><br />Because the Mentor works within the same teaching framework developed around Shaanzae's methods, the advice is not disconnected AI commentary. It becomes part of a continuing learning journey.</>} /><p className="mentor-conclusion">Your next lesson is informed by the writer you are becoming, not treated as if HIRI has never seen your work before.</p><p className="sample-emphasis">The aim is not simply to produce a better submission. It is to develop a better writer.</p></section>

    <section className="section teaching-centre"><SectionHeading eyebrow="The teaching behind HIRI" title="Shaanzae's method stays at the centre." description={<>HIRI extends Shaanzae's teaching beyond the video lesson.<br /><br />The Coach examines how you applied the skill in your current writing.<br />The Mentor looks across your development and helps identify what to work on next.<br />Both are designed around the same teaching approach that guides the course.</>} /><p className="sample-credentials">Published author • Cambridge PGCert • Former Head of English</p><p className="sample-emphasis">Human teaching, extended through intelligent personal support.</p></section>

    <section className="section"><div className="cta-band"><p className="eyebrow">Ready to experience the full course?</p><h2>One lesson changes how you see your writing. Four weeks changes how you write.</h2><p>HIRI gives you sixteen guided lessons, structured practice, personalised feedback and a Coach and Mentor that continue supporting your development from one lesson to the next.</p><div className="hero-actions"><ButtonLink href="https://app.hiri.uk/enroll" variant="secondary">Enroll Now</ButtonLink><ButtonLink href="/course" variant="ghost">View Course</ButtonLink></div></div></section>
  </Container></div>;
}
